language: node_js
node_js:
- 10.1.0
script:
- ".travis/init.sh"
- ROOT_PATH=nixpkgs-ruby/versions npm start
- ".travis/push.sh"
cache:
  directories:
  - node_modules
env:
  global:
    secure: xTpwW49FPllNnBp9gKaApBAK7E3hcqSJpMJH5FjIWPpeeDstW/5MHvysRsHX88ih9+tL/qBPCUKRH2e2eq4Jl90OF4ceTbLVtXiA98TT9O8kc9lYv8tTjLh7uRQ7SXgRAJsvCEwhYq5r8G3oye2w2l15pbtHa8L/yLpmPGthKzl6C9xgZ7f8ZOp/K35pM9/0KmGfdrPBQvPt1Hxoo4Hbmcq0nCR1SQzKzw458oQ4815aZuQj4gUaP8xi4do5P6qa7+t+F3Y7rVvUPr3W+voHo9cjDVIljF7vSryB0cGO3w98de8KjvrWk+YSH+/ZJeSw64j/VThBY0V76WE49uLiRL6efu+WCL4l2dNyBOSkelGCkdLnEs3A6bj16QG/ohm7x2VA7Dc7awRANyavgraOSlpDun9g0fPzVm+o23BO+zK7dRdWAzkI2oIDnDFv/SpykS0Bdcz2wHu42mro48aW5mjO4yIEay0hd86mABFwfgNGuPS5VGyJ+XoOLPW23eZoUq0opCsJT40bz7412FP6q8/r4XFjnv9Mp0akn6p7BKSIJ0yN5sFWs+DSjb3KTbkjCXIZgsXuSJN1YA6RncDTfm0HisQVPmDud5EcIARmBOW5hXQZFMpZs7F9fov+OA6bI88R+DApsrrp9PdJSBF7YbiXxsYXWkpfv1bHSjGXAKg=
