language: node_js
node_js:
- '0.11'
- '0.10'
script:
- ".travis/init.sh"
- ROOT_PATH=nixpkgs-ruby/versions npm start
- ".travis/push.sh"
cache:
  directories:
  - node_modules
env:
  global:
    secure: TR2Y6XkuZAdEj2aFzTv9G8J7NEaXDPZlrQDJycjTiz36ilg/WV7815t6jgxmXqJp2VzVuh+C64sP2Xp3aYk7LZg/U/95fKnBKFY7AenuUObGNGAM5t5xqWp25QpMOGunjTDiSEot9YXxn7RwOSdrjMfbTJrqnXE8pfRytCiiSTrSItaD4dnacWHPty172ewjmvplceuZae86xMYYugjGobbRCtID1dkOGnIfDzKr82I7kin2nVqhm+Fh74+XIMIbgncIajDe5pchhcVt4X0X3JEwcH/+e0UJqcEiWfVsKGF3u/uZskcoTRx9gTRi8xTY7e24P5DVwfGLqB5JCjg/RkyH4Y/fUHRXt/cBCy+SI+IiPLc2I5sLWgEUHlqR5dcTIBA7vztwyNTHi7aFIKQ+20BFQVsApr84R2OE9rKdQOF1ChLiUFlC42SkeX/DOX6xywurXdNkbm8DmDygZ+ZX0oVRtk5AX0S4jM3NF/xVIyFUv82pQl5d15/TtoaAVLWiHFePTOmeTw37OQdY8DE5aLEHDo1aSV35i0JBHj9rtE3zTuXboCWI8q4X23XYPLYOhsxZbYjPjU96/6Om04h+9GJwttT5b66FSrtH8zZiXpbgPAaNF7rVRBsSP9k1QxLg6cNZgLt2JZb84zoI4QHoXhMQVXI0Jf576j4afbbkKqU=
